- name: web server installation
  hosts: all
  become: yes
  gather_facts: true

  tasks:
    - name: Amazon tasks
      include_tasks: amazon.yml
      when: ansible_distribution == 'Amazon'

    - name: Ubuntu tasks
      include_tasks: ubuntu.yml
      when: ansible_distribution == 'Ubuntu'