- name: stop, remove web
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Amazon > stop httpd
      service: name=httpd state=stopped
      when: ansible_distribution == 'Amazon'

    - name: Amazon > remove httpd
      action: "yum name=httpd state=absent"
      when: ansible_distribution == 'Amazon'

    - name: Ubuntu > stop nginx
      service: name=nginx state=stopped
      when: ansible_distribution == 'Ubuntu'

    - name: Ubuntu > remove nginx
      action: "apt name=nginx state=absent purge=yes autoremove=yes"
      when: ansible_distribution == 'Ubuntu'
