- name: stop, remove web
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Rocky > stop httpd
      service: name=httpd state=stopped
      when: ansible_distribution == 'Rocky'

    - name: Rocky > remove httpd
      action: "{{ ansible_pkg_mgr }} name=httpd state=absent"
      when: ansible_distribution == 'Rocky'

    - name: Ubuntu > stop nginx
      service: name=nginx state=stopped
      when: ansible_distribution == 'Ubuntu'

    - name: Ubuntu > remove nginx
      action: "{{ ansible_pkg_mgr }} name=nginx state=absent purge=yes autoremove=yes"
      when: ansible_distribution == 'Ubuntu'
